AWSTemplateFormatVersion: "2010-09-09"

Description: My sam app
Resources:
  Lambda1FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: lambda1-access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sns:*
                  - s3:*
                  - codepipeline:PutJobSuccessResult
                  - codepipeline:PutJobFailureResult
                Resource: "*"
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: "*"

  Lambda1Function:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../../project1
      Handler: lambda1.handle
      Role: !GetAtt Lambda1FunctionRole.Arn
      Runtime: python3.8
      Timeout: 10
